#!/bin/sh

echo '--------------------------'
echo 'Running go linter'

golangci-lint run

echo '--------------------------'
echo 'Running Testing'

go test -v ./handlers
go test -v ./utils

echo '--------------------------'